#!/usr/bin/env python3
"""Generate a Win32 resource archive and lookup table for the web runtime."""

from __future__ import annotations

import argparse
import json
import mimetypes
from pathlib import Path


INCLUDED_TOP_LEVEL = {
    "assets", "audio", "bitmaps", "cgpk", "help", "palettes", "raw", "strings", "win16-ui",
}


def should_include(relative: Path) -> bool:
    if relative.name.endswith(".map"):
        return False
    if len(relative.parts) == 1:
        return relative.name in {"index.html", "catalog.json"}
    return relative.parts[0] in INCLUDED_TOP_LEVEL


def mime_type(path: Path) -> str:
    overrides = {
        ".js": "text/javascript; charset=utf-8",
        ".css": "text/css; charset=utf-8",
        ".html": "text/html; charset=utf-8",
        ".json": "application/json; charset=utf-8",
        ".wav": "audio/wav",
        ".raw": "application/octet-stream",
    }
    return overrides.get(path.suffix.lower(), mimetypes.guess_type(path.name)[0] or "application/octet-stream")


def c_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("dist", type=Path)
    parser.add_argument("rc", type=Path)
    parser.add_argument("header", type=Path)
    args = parser.parse_args()

    dist = args.dist.resolve()
    files = sorted(
        path for path in dist.rglob("*")
        if path.is_file() and should_include(path.relative_to(dist))
    )
    if not files:
        raise SystemExit(f"no distributable assets found below {dist}")

    args.rc.parent.mkdir(parents=True, exist_ok=True)
    rc_lines = ["// Generated by tools/embed_web_assets.py.\n"]
    app_icon = dist / "win16-ui" / "icons" / "TOWER_APPICON.ico"
    if app_icon.exists():
        escaped_icon = app_icon.as_posix().replace('"', '""')
        rc_lines.append(f'1 ICON "{escaped_icon}"\n')
    header_lines = [
        "// Generated by tools/embed_web_assets.py.\n",
        "#pragma once\n",
        "\n",
        "struct EmbeddedAsset {\n",
        "  const char* path;\n",
        "  int resource_id;\n",
        "  const char* content_type;\n",
        "};\n",
        "\n",
        "inline constexpr EmbeddedAsset kEmbeddedAssets[] = {\n",
    ]
    total_bytes = 0
    for resource_id, source in enumerate(files, 1000):
        relative = source.relative_to(dist).as_posix()
        url_path = "/" + relative
        escaped_source = source.as_posix().replace('"', '""')
        rc_lines.append(f'{resource_id} RCDATA "{escaped_source}"\n')
        header_lines.append(
            f"  {{{c_string(url_path)}, {resource_id}, {c_string(mime_type(source))}}},\n"
        )
        total_bytes += source.stat().st_size
    header_lines.extend(
        [
            "};\n",
            "inline constexpr unsigned int kEmbeddedAssetCount = ",
            "sizeof(kEmbeddedAssets) / sizeof(kEmbeddedAssets[0]);\n",
        ]
    )
    args.rc.write_text("".join(rc_lines), encoding="utf-8")
    args.header.write_text("".join(header_lines), encoding="utf-8")
    print(f"embedded {len(files)} files ({total_bytes} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
